-- Copyright (C) 2018  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Intel Program License 
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel FPGA IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Intel and sold by Intel or its authorized distributors.  Please
-- refer to the applicable agreement for further details.

-- PROGRAM		"Quartus Prime"
-- VERSION		"Version 18.1.0 Build 625 09/12/2018 SJ Lite Edition"
-- CREATED		"Sat Aug 08 12:54:00 2026"

LIBRARY ieee;
USE ieee.std_logic_1164.all; 

LIBRARY work;

ENTITY Desacople6R_Top IS 
	PORT
	(
		clk :  IN  STD_LOGIC;
		reset :  IN  STD_LOGIC;
		Start :  IN  STD_LOGIC;
		R11_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		R12_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		R13_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		R21_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		R22_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		R23_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		R31_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		R32_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		R33_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		x_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		y_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		z_d :  IN  STD_LOGIC_VECTOR(15 DOWNTO 0);
		Desacople_Listo :  OUT  STD_LOGIC;
		tetha1Final :  OUT  STD_LOGIC_VECTOR(15 DOWNTO 0);
		tetha2Final :  OUT  STD_LOGIC_VECTOR(15 DOWNTO 0);
		tetha3Final :  OUT  STD_LOGIC_VECTOR(15 DOWNTO 0);
		tetha4Final :  OUT  STD_LOGIC_VECTOR(15 DOWNTO 0);
		tetha5Final :  OUT  STD_LOGIC_VECTOR(15 DOWNTO 0);
		tetha6Final :  OUT  STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END Desacople6R_Top;

ARCHITECTURE bdf_type OF Desacople6R_Top IS 

COMPONENT cinematica_inversa3r
	PORT(clk : IN STD_LOGIC;
		 reset : IN STD_LOGIC;
		 Start : IN STD_LOGIC;
		 Px_d : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 Py_d : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 Pz_d : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 Ik3R_Ready : OUT STD_LOGIC;
		 tetha_one : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 tetha_three : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 tetha_two : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT wrist_center
	PORT(clk : IN STD_LOGIC;
		 rst : IN STD_LOGIC;
		 start : IN STD_LOGIC;
		 dx : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 dy : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 dz : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 rz_x : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 rz_y : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 rz_z : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 done : OUT STD_LOGIC;
		 Px_d : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 Py_d : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 Pz_d : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT r03_builder
	PORT(clk : IN STD_LOGIC;
		 rst : IN STD_LOGIC;
		 start : IN STD_LOGIC;
		 theta1 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 theta2 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 theta3 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 done : OUT STD_LOGIC;
		 r03_11 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r03_12 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r03_13 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r03_21 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r03_22 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r03_23 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r03_31 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r03_32 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r03_33 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT mat3_transpose
	PORT(clk : IN STD_LOGIC;
		 rst : IN STD_LOGIC;
		 start : IN STD_LOGIC;
		 a11 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a12 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a13 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a21 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a22 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a23 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a31 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a32 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a33 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 done : OUT STD_LOGIC;
		 t11 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 t12 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 t13 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 t21 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 t22 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 t23 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 t31 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 t32 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 t33 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT mat3x3_mult
	PORT(clk : IN STD_LOGIC;
		 rst : IN STD_LOGIC;
		 start : IN STD_LOGIC;
		 a11 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a12 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a13 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a21 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a22 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a23 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a31 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a32 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 a33 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 b11 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 b12 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 b13 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 b21 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 b22 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 b23 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 b31 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 b32 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 b33 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 done : OUT STD_LOGIC;
		 c11 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 c12 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 c13 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 c21 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 c22 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 c23 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 c31 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 c32 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 c33 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

COMPONENT wristangles3r
	PORT(clk : IN STD_LOGIC;
		 rst : IN STD_LOGIC;
		 start : IN STD_LOGIC;
		 r13 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r23 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r31 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r32 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 r33 : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		 done : OUT STD_LOGIC;
		 theta4 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 theta5 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		 theta6 : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
	);
END COMPONENT;

SIGNAL	SYNTHESIZED_WIRE_0 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_1 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_2 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_3 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_4 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_5 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_6 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_7 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_8 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_9 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_10 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_11 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_12 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_13 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_14 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_15 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_16 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_17 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_18 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_19 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_20 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_21 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_22 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_23 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_24 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_25 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_26 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_27 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_28 :  STD_LOGIC;
SIGNAL	SYNTHESIZED_WIRE_29 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_30 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_31 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_32 :  STD_LOGIC_VECTOR(15 DOWNTO 0);
SIGNAL	SYNTHESIZED_WIRE_33 :  STD_LOGIC_VECTOR(15 DOWNTO 0);


BEGIN 
tetha1Final <= SYNTHESIZED_WIRE_5;
tetha2Final <= SYNTHESIZED_WIRE_6;
tetha3Final <= SYNTHESIZED_WIRE_7;



b2v_inst : cinematica_inversa3r
PORT MAP(clk => clk,
		 reset => reset,
		 Start => SYNTHESIZED_WIRE_0,
		 Px_d => SYNTHESIZED_WIRE_1,
		 Py_d => SYNTHESIZED_WIRE_2,
		 Pz_d => SYNTHESIZED_WIRE_3,
		 Ik3R_Ready => SYNTHESIZED_WIRE_4,
		 tetha_one => SYNTHESIZED_WIRE_5,
		 tetha_three => SYNTHESIZED_WIRE_7,
		 tetha_two => SYNTHESIZED_WIRE_6);


b2v_inst1 : wrist_center
PORT MAP(clk => clk,
		 rst => reset,
		 start => Start,
		 dx => x_d,
		 dy => y_d,
		 dz => z_d,
		 rz_x => R13_d,
		 rz_y => R23_d,
		 rz_z => R33_d,
		 done => SYNTHESIZED_WIRE_0,
		 Px_d => SYNTHESIZED_WIRE_1,
		 Py_d => SYNTHESIZED_WIRE_2,
		 Pz_d => SYNTHESIZED_WIRE_3);


b2v_inst2 : r03_builder
PORT MAP(clk => clk,
		 rst => reset,
		 start => SYNTHESIZED_WIRE_4,
		 theta1 => SYNTHESIZED_WIRE_5,
		 theta2 => SYNTHESIZED_WIRE_6,
		 theta3 => SYNTHESIZED_WIRE_7,
		 done => SYNTHESIZED_WIRE_8,
		 r03_11 => SYNTHESIZED_WIRE_9,
		 r03_12 => SYNTHESIZED_WIRE_10,
		 r03_13 => SYNTHESIZED_WIRE_11,
		 r03_21 => SYNTHESIZED_WIRE_12,
		 r03_22 => SYNTHESIZED_WIRE_13,
		 r03_23 => SYNTHESIZED_WIRE_14,
		 r03_31 => SYNTHESIZED_WIRE_15,
		 r03_32 => SYNTHESIZED_WIRE_16,
		 r03_33 => SYNTHESIZED_WIRE_17);


b2v_inst3 : mat3_transpose
PORT MAP(clk => clk,
		 rst => reset,
		 start => SYNTHESIZED_WIRE_8,
		 a11 => SYNTHESIZED_WIRE_9,
		 a12 => SYNTHESIZED_WIRE_10,
		 a13 => SYNTHESIZED_WIRE_11,
		 a21 => SYNTHESIZED_WIRE_12,
		 a22 => SYNTHESIZED_WIRE_13,
		 a23 => SYNTHESIZED_WIRE_14,
		 a31 => SYNTHESIZED_WIRE_15,
		 a32 => SYNTHESIZED_WIRE_16,
		 a33 => SYNTHESIZED_WIRE_17,
		 done => SYNTHESIZED_WIRE_18,
		 t11 => SYNTHESIZED_WIRE_19,
		 t12 => SYNTHESIZED_WIRE_20,
		 t13 => SYNTHESIZED_WIRE_21,
		 t21 => SYNTHESIZED_WIRE_22,
		 t22 => SYNTHESIZED_WIRE_23,
		 t23 => SYNTHESIZED_WIRE_24,
		 t31 => SYNTHESIZED_WIRE_25,
		 t32 => SYNTHESIZED_WIRE_26,
		 t33 => SYNTHESIZED_WIRE_27);


b2v_inst4 : mat3x3_mult
PORT MAP(clk => clk,
		 rst => reset,
		 start => SYNTHESIZED_WIRE_18,
		 a11 => SYNTHESIZED_WIRE_19,
		 a12 => SYNTHESIZED_WIRE_20,
		 a13 => SYNTHESIZED_WIRE_21,
		 a21 => SYNTHESIZED_WIRE_22,
		 a22 => SYNTHESIZED_WIRE_23,
		 a23 => SYNTHESIZED_WIRE_24,
		 a31 => SYNTHESIZED_WIRE_25,
		 a32 => SYNTHESIZED_WIRE_26,
		 a33 => SYNTHESIZED_WIRE_27,
		 b11 => R11_d,
		 b12 => R12_d,
		 b13 => R13_d,
		 b21 => R21_d,
		 b22 => R22_d,
		 b23 => R23_d,
		 b31 => R31_d,
		 b32 => R32_d,
		 b33 => R33_d,
		 done => SYNTHESIZED_WIRE_28,
		 c13 => SYNTHESIZED_WIRE_29,
		 c23 => SYNTHESIZED_WIRE_30,
		 c31 => SYNTHESIZED_WIRE_31,
		 c32 => SYNTHESIZED_WIRE_32,
		 c33 => SYNTHESIZED_WIRE_33);


b2v_inst5 : wristangles3r
PORT MAP(clk => clk,
		 rst => reset,
		 start => SYNTHESIZED_WIRE_28,
		 r13 => SYNTHESIZED_WIRE_29,
		 r23 => SYNTHESIZED_WIRE_30,
		 r31 => SYNTHESIZED_WIRE_31,
		 r32 => SYNTHESIZED_WIRE_32,
		 r33 => SYNTHESIZED_WIRE_33,
		 done => Desacople_Listo,
		 theta4 => tetha4Final,
		 theta5 => tetha5Final,
		 theta6 => tetha6Final);


END bdf_type;